"""
    build_mex(f;
        input_types,
        output_types,
        name        = nothing,
        output      = ".",
        trim        = true,
        bundle      = true,
        juliac_bin  = "juliac",
    )

Compile Julia function `f` into a MATLAB MEX extension in `output/`.

# Arguments
- `f` — any Julia function. Must have a single method matching `input_types`.
- `input_types` — `Vector{Type}` of concrete argument types.
- `output_types` — `Vector{Type}` of concrete return types.
- `name` — MATLAB-visible name (default: `nameof(f)`).
- `output` — directory where the `.mex*` file and bundle land.
- `trim` — pass `--trim=safe` to juliac (recommended; much smaller binaries).
- `bundle` — pass `--bundle output` to juliac so `libjulia.so` is co-located.
- `juliac_bin` — path or name of the juliac executable.

# Output
Writes `output/<name>.<mex_ext>` and, when `bundle=true`, `libjulia.so` and
friends into `output/`. Also writes `output/mexicah_setup.m` which the MATLAB
user runs once per session to put the bundle directory on `LD_LIBRARY_PATH`.
"""
function build_mex(
        f;
        input_types::Vector{<:Type},
        output_types::Vector{<:Type},
        name::Union{Symbol, Nothing} = nothing,
        output::String = ".",
        trim::Bool = true,
        bundle::Bool = true,
        juliac_bin::String = "juliac",
    )::String
    func_name = name === nothing ? nameof(f) : name
    func_module = parentmodule(f)

    _validate_method(f, input_types)

    mkpath(output)

    src = generate_mex_source(
        func_module,
        func_name,
        Vector{Type}(input_types),
        Vector{Type}(output_types),
        func_name,
    )

    generated_jl = joinpath(output, "$(func_name)_mexgen.jl")
    write(generated_jl, src)

    _format_file(generated_jl)

    ext = mex_ext()
    out_mex = joinpath(output, "$(func_name).$ext")
    tmp_lib = joinpath(output, "$(func_name)_tmp.so")

    args = String[juliac_bin, "--output-lib", tmp_lib]
    trim && push!(args, "--trim=safe")
    bundle && append!(args, ["--bundle", output])
    # macOS linker rejects undefined symbols by default; tell it to resolve them
    # at load time from the MATLAB process image (same as ELF lazy binding on Linux).
    Sys.isapple() && append!(args, ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"])
    push!(args, generated_jl)

    @info "Mexicah: compiling $(func_name) with juliac…"
    run(Cmd(args))

    mv(tmp_lib, out_mex; force = true)
    @info "Mexicah: wrote $out_mex"

    _write_setup_m(output, func_name)

    return out_mex
end

# ── Helpers ───────────────────────────────────────────────────────────────────

"""
    _infer_vector_input(f) -> Type or nothing

Return `Vector{Float64}` if `f` has a method accepting a single `Vector{Float64}`
argument, otherwise `nothing`. Used by `@mexgradient` to validate gradient targets.
"""
function _infer_vector_input(f)::Union{Type, Nothing}
    hasmethod(f, Tuple{Vector{Float64}}) && return Vector{Float64}
    return nothing
end

function _validate_method(f, input_types::Vector{<:Type})
    sig = Tuple{typeof(f), input_types...}
    if !hasmethod(f, Tuple{input_types...})
        error(
            "Mexicah: no method found for $(nameof(f)) with types $(join(input_types, ", ")). " *
                "Ensure the function has a concrete method matching these argument types.",
        )
    end
    # Check that inference produces a concrete result (not Any) to warn early.
    rt = only(Base.return_types(f, Tuple{input_types...}))
    return if rt === Any || rt === Union{}
        @warn "Mexicah: return type inferred as $rt for $(nameof(f)). " *
            "juliac --trim=safe may fail. Add explicit return type annotations."
    end
end

function _format_file(path::String)::Cvoid
    result = run(ignorestatus(`runic -i $path`))
    result.exitcode != 0 && @warn "Mexicah: runic formatting failed for $path (exit $(result.exitcode))"
    return
end

function _write_setup_m(output_dir::String, func_name::Symbol)::Cvoid
    abs_dir = abspath(output_dir)
    content = """
    % mexicah_setup.m — run this once per MATLAB session before calling MEX functions.
    % Generated by Mexicah.jl for: $func_name

    bundle_dir = '$(escape_string(abs_dir))';
    if isunix
        cur = getenv('LD_LIBRARY_PATH');
        if isempty(cur)
            setenv('LD_LIBRARY_PATH', bundle_dir);
        elseif ~contains(cur, bundle_dir)
            setenv('LD_LIBRARY_PATH', [bundle_dir ':' cur]);
        end
    elseif ismac
        cur = getenv('DYLD_LIBRARY_PATH');
        if isempty(cur)
            setenv('DYLD_LIBRARY_PATH', bundle_dir);
        elseif ~contains(cur, bundle_dir)
            setenv('DYLD_LIBRARY_PATH', [bundle_dir ':' cur]);
        end
    end
    addpath(bundle_dir);
    """
    write(joinpath(output_dir, "mexicah_setup.m"), content)
    return
end
