# Generates a self-contained Julia source file that, when compiled with
#   juliac --output-lib <name>.so --trim=safe <generated>.jl
# produces a MEX-loadable shared library exporting the symbol `mexFunction`.

"""
    generate_mex_source(func_module, func_name, argtypes, rettypes, mex_name) -> String

Return the source text of a complete Julia file that wraps `func_module.func_name`
with a `@ccallable mexFunction` entry point. The caller writes this to a `.jl` file
and passes it to `juliac`.
"""
function generate_mex_source(
        func_module::Module,
        func_name::Symbol,
        argtypes::Vector{Type},
        rettypes::Vector{Type},
        mex_name::Symbol,
    )::String
    mod_name = nameof(func_module)
    return """
    # AUTO-GENERATED by Mexicah.jl — do not edit by hand.
    using Mexicah
    import $mod_name

    $(_gen_ccallable(:mexFunction, mod_name, func_name, argtypes, rettypes))
    """
end

"""
    generate_shared_mex_source(entries) -> String

Return one Julia file exporting a separate `@ccallable mexFunction_<name>` entry
per registered function. juliac compiles it into ONE shared library; each thin
gateway dlopens that single library (so the Julia runtime initializes exactly
once) and calls its own entry. This is what lets several Mexicah MEX coexist in
one MATLAB session.

`entries` is a vector of `(func_module::Module, func_name::Symbol,
argtypes::Vector{Type}, rettypes::Vector{Type})`.
"""
function generate_shared_mex_source(
        entries::Vector{<:Tuple{Module, Symbol, Vector{Type}, Vector{Type}}},
    )::String
    mods = unique(nameof(e[1]) for e in entries)
    imports = join(("import $m" for m in mods), "\n")
    bodies = join(
        (
            _gen_ccallable(_entry_symbol(e[2]), nameof(e[1]), e[2], e[3], e[4])
                for e in entries
        ),
        "\n\n",
    )
    return """
    # AUTO-GENERATED by Mexicah.jl — do not edit by hand.
    using Mexicah
    $imports

    $bodies
    """
end

# The C entry-point symbol a gateway dlsym()s for function `name`.
_entry_symbol(name::Symbol)::Symbol = Symbol("mexFunction_", name)

# One `@ccallable` MEX entry point named `entry`, wrapping `mod_name.func_name`.
function _gen_ccallable(
        entry::Symbol,
        mod_name::Symbol,
        func_name::Symbol,
        argtypes::Vector{Type},
        rettypes::Vector{Type},
    )::String
    nargs = length(argtypes)
    nret = length(rettypes)
    load_stmts = _gen_load_stmts(argtypes)
    call_stmt = _gen_call_stmt(mod_name, func_name, nargs, rettypes)
    store_stmts = _gen_store_stmts(rettypes)
    check_stmt = _gen_arg_check(nargs, nret)
    return """
    Base.@ccallable function $entry(
            nlhs::Cint,
            plhs::Ptr{Mexicah.MxArray},
            nrhs::Cint,
            prhs::Ptr{Mexicah.MxArray},
        )::Cvoid
        Mexicah._mexicah_init_once()
    $check_stmt
    $load_stmts
    $call_stmt
    $store_stmts
        return
    end"""
end

# ── Internal helpers ──────────────────────────────────────────────────────────

function _gen_arg_check(nargs::Int, nret::Int)::String
    return """    if nrhs != $nargs
        Mexicah.mex_errorf(
            "Mexicah:argCount",
            "Expected $nargs input(s), got " * string(Int(nrhs)),
        )
    end
    if nlhs > $nret
        Mexicah.mex_errorf(
            "Mexicah:retCount",
            "Expected at most $nret output(s), got " * string(Int(nlhs)),
        )
    end"""
end

function _gen_load_stmts(argtypes::Vector{Type})::String
    lines = String[]
    for (i, T) in enumerate(argtypes)
        tname = _type_literal(T)
        push!(lines, "    _arg$i = Mexicah.load_arg(prhs, $i, $tname)")
    end
    return join(lines, "\n")
end

# Qualify the call as `Module.func` so juliac resolves it via the `import Module`
# in the generated source. An unqualified name would resolve to the compilation
# process's (empty) Main and fail trim verification.
function _gen_call_stmt(mod_name::Symbol, func_name::Symbol, nargs::Int, rettypes::Vector{Type})::String
    args = join(["_arg$i" for i in 1:nargs], ", ")
    callee = "$mod_name.$func_name"
    return if length(rettypes) == 1
        "    _ret1 = $callee($args)"
    elseif length(rettypes) > 1
        lhs = join(["_ret$i" for i in 1:length(rettypes)], ", ")
        "    ($lhs,) = $callee($args)"
    else
        "    $callee($args)"
    end
end

function _gen_store_stmts(rettypes::Vector{Type})::String
    lines = String[]
    for (i, T) in enumerate(rettypes)
        tname = _type_literal(T)
        push!(lines, "    Mexicah.store_result(plhs, $i, _ret$i::$tname)")
    end
    return join(lines, "\n")
end

function _type_literal(T::Type)::String
    T === Float64 && return "Float64"
    T === Vector{Float64} && return "Vector{Float64}"
    T === Matrix{Float64} && return "Matrix{Float64}"
    T === Int32 && return "Int32"
    T === Int64 && return "Int64"
    T === UInt64 && return "UInt64"
    T === Bool && return "Bool"
    # Qualify via Mexicah (which imports SparseMatrixCSC): the generated MEX
    # source only does `using Mexicah`, so `SparseArrays` is not in scope there.
    T === SparseMatrixCSC{Float64, Int} && return "Mexicah.SparseMatrixCSC{Float64,Int}"
    T === Vector{ComplexF64} && return "Vector{ComplexF64}"
    T === String && return "String"
    error("Mexicah codegen: unsupported type $T")
end
