# Generates a self-contained Julia source file that, when compiled with
#   juliac --output-lib <name>.so --trim=safe <generated>.jl
# produces a MEX-loadable shared library exporting the symbol `mexFunction`.

"""
    generate_mex_source(func_module, func_name, argtypes, rettypes, mex_name) -> String

Return the source text of a complete Julia file that wraps `func_module.func_name`
with a `@ccallable mexFunction` entry point. The caller writes this to a `.jl` file
and passes it to `juliac`.
"""
function generate_mex_source(
        func_module::Module,
        func_name::Symbol,
        argtypes::Vector{Type},
        rettypes::Vector{Type},
        mex_name::Symbol,
    )::String
    mod_name = nameof(func_module)
    nargs = length(argtypes)
    nret = length(rettypes)

    load_stmts = _gen_load_stmts(argtypes)
    call_stmt = _gen_call_stmt(func_name, nargs, rettypes)
    store_stmts = _gen_store_stmts(rettypes)
    check_stmt = _gen_arg_check(nargs, nret)

    return """
    # AUTO-GENERATED by Mexicah.jl — do not edit by hand.
    using Mexicah
    import $mod_name

    Base.@ccallable function mexFunction(
        nlhs::Cint,
        plhs::Ptr{Ptr{Mexicah.MxArray}},
        nrhs::Cint,
        prhs::Ptr{Ptr{Mexicah.MxArray}},
    )::Cvoid
        Mexicah._mexicah_init_once()
    $check_stmt
    $load_stmts
    $call_stmt
    $store_stmts
        return
    end
    """
end

# ── Internal helpers ──────────────────────────────────────────────────────────

function _gen_arg_check(nargs::Int, nret::Int)::String
    return """    if nrhs != $nargs
        Mexicah.mex_errorf(
            "Mexicah:argCount",
            "Expected $nargs input(s), got " * string(Int(nrhs)),
        )
    end
    if nlhs > $nret
        Mexicah.mex_errorf(
            "Mexicah:retCount",
            "Expected at most $nret output(s), got " * string(Int(nlhs)),
        )
    end"""
end

function _gen_load_stmts(argtypes::Vector{Type})::String
    lines = String[]
    for (i, T) in enumerate(argtypes)
        tname = _type_literal(T)
        push!(lines, "    _arg$i = Mexicah.load_arg(prhs, $i, $tname)")
    end
    return join(lines, "\n")
end

function _gen_call_stmt(func_name::Symbol, nargs::Int, rettypes::Vector{Type})::String
    args = join(["_arg$i" for i in 1:nargs], ", ")
    return if length(rettypes) == 1
        "    _ret1 = $func_name($args)"
    elseif length(rettypes) > 1
        lhs = join(["_ret$i" for i in 1:length(rettypes)], ", ")
        "    ($lhs,) = $func_name($args)"
    else
        "    $func_name($args)"
    end
end

function _gen_store_stmts(rettypes::Vector{Type})::String
    lines = String[]
    for (i, T) in enumerate(rettypes)
        tname = _type_literal(T)
        push!(lines, "    Mexicah.store_result(plhs, $i, _ret$i::$tname)")
    end
    return join(lines, "\n")
end

function _type_literal(T::Type)::String
    T === Float64 && return "Float64"
    T === Vector{Float64} && return "Vector{Float64}"
    T === Matrix{Float64} && return "Matrix{Float64}"
    T === Int32 && return "Int32"
    T === Int64 && return "Int64"
    T === UInt64 && return "UInt64"
    T === Bool && return "Bool"
    T === SparseMatrixCSC{Float64, Int} && return "SparseArrays.SparseMatrixCSC{Float64,Int}"
    T === Vector{ComplexF64} && return "Vector{ComplexF64}"
    T === String && return "String"
    error("Mexicah codegen: unsupported type $T")
end
